In [1]:
import numpy as np
import pandas as pd

dfTrain = pd.read_csv('../../../DataSet/trip_train.csv', parse_dates=['start_date', 'end_date'], infer_datetime_format=True)
dfTest = pd.read_csv('../../../DataSet/trip_test.csv', parse_dates=['start_date', 'end_date'], infer_datetime_format=True)

In [2]:
dfTrain.drop(['id', 'start_station_name', 
              'end_date', 'end_station_name', 
              'end_station_id', 'zip_code', 'bike_id'], axis=1, inplace=True)

target = dfTrain.duration
dfTrain.drop(['duration'], axis=1, inplace=True)
dfTrain.head(8)

           start_date  start_station_id subscription_type
0 2015-08-27 08:36:00                50        Subscriber
1 2014-07-28 22:06:00                67        Subscriber
2 2014-06-09 08:42:00                77        Subscriber
3 2015-01-26 16:55:00                69        Subscriber
4 2015-08-29 15:09:00                67        Subscriber
5 2014-10-30 07:00:00                65        Subscriber
6 2015-08-07 17:11:00                64        Subscriber
7 2014-10-08 14:10:00                71        Subscriber

In [3]:
trainDateData = {'start_month':dfTrain.start_date.dt.month,
                     'start_dayOfYear':dfTrain.start_date.dt.dayofyear,
                     'start_dayOfWeek':dfTrain.start_date.dt.dayofweek,
                     'start_hourOfDay':dfTrain.start_date.dt.hour}

dfTrain = dfTrain[['start_station_id', 'subscription_type']].join(pd.DataFrame(trainDateData))

subscriptionTypes = dfTrain.subscription_type.unique()
dfTrain.subscription_type = dfTrain.subscription_type.astype('category', categories=subscriptionTypes).cat.codes
dfTest.subscription_type = dfTest.subscription_type.astype('category', categories=subscriptionTypes).cat.codes
dfTrain.head(12)

,start_station_id,subscription_type,start_dayOfWeek,start_dayOfYear,start_hourOfDay,start_month
0,50,0,3,239,8,8
1,67,0,0,209,22,7
2,77,0,0,160,8,6
3,69,0,0,26,16,1
4,67,0,5,241,15,8
5,65,0,3,303,7,10
6,64,0,4,219,17,8
7,71,0,2,281,14,10
8,62,0,4,233,7,8
9,76,1,3,113,6,4
10,70,0,1,140,8,5
11,77,0,4,171,11,6